#!/bin/sh
PHP_INI_SCAN_DIR='/var/www/u2946871/data/php-bin-php83-ioncube/tovarum.com:'
PHPRC='/var/www/u2946871/data/php-bin-php83-ioncube'
export PHP_INI_SCAN_DIR
export PHPRC
exec /opt/php/8.3-ioncube/bin/php-cgi
