#!/bin/sh
PHP_INI_SCAN_DIR='/var/www/u2946871/data/php-bin-regru-php83/test.tovarum.ru:'
PHPRC='/var/www/u2946871/data/php-bin-regru-php83'
export PHP_INI_SCAN_DIR
export PHPRC
exec /opt/php/8.3/bin/php-cgi
